name: Generate macOS Tahoe Recovery Image

on:
  workflow_dispatch:

run-name: Generate macOS Tahoe Recovery Image


jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      

      - name: Download macOS Installer
        run: |
          curl -L -o /tmp/InstallAssistant.pkg https://swcdn.apple.com/content/downloads/11/14/093-37361-A_NX0SMZC0LI/9slwkknt5xciy7bhd9ux9utct03e07j6qp/InstallAssistant.pkg

      - name: Install the assistant
        run: |
          sudo installer -pkg /tmp/InstallAssistant.pkg -target /

      - name: Generate macOS Installer
        run: |
          sudo hdiutil create -o /tmp/Tahoe -size 20000m -volname 'Tahoe' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/Tahoe.dmg -noverify -mountpoint /Volumes/Tahoe
          sleep 10
          sudo /Applications/'Install macOS Tahoe'.app/Contents/Resources/createinstallmedia --volume /Volumes/Tahoe --nointeraction
          cp -R '/Volumes/Install macOS Tahoe/BaseSystem' /tmp/BaseSystem

      - name: Upload com.apple.recovery.boot
        uses: actions/upload-artifact@v4
        with:
          name: com.apple.recovery.boot
          path: /tmp/BaseSystem/*
          compression-level: 9
